# Generated by Django 4.2 on 2023-04-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
